version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      ISSUER_BASE_URL: ${OIDC_ISSUER_BASE_URL:-http://oidc-mock:9090}
      CLIENT_ID: ${OIDC_CLIENT_ID:-coronatests}
      BASE_URL: ${OIDC_APP_BASE_URL:-http://localhost:8080/api}
      SECRET: ${OIDC_APP_SECRET?err}

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile-test
    restart: unless-stopped
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: test
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

  oidc-mock:
    build:
      context: ./oidc-mock
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${OIDC_PORT:-9090}:9090"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-web
    restart: unless-stopped
    volumes:
      - ./web/proxy/development:/etc/nginx/templates
    ports:
      - "${WEB_PORT:-8080}:80"

  web-admin:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-admin
    restart: unless-stopped
    volumes:
      - ./web/adminfrontend:/app
      - ./web/shared:/shared
    environment:
      NODE_ENV: development

  web-user:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-user
    restart: unless-stopped
    volumes:
      - ./web/userfrontend:/app
      - ./web/shared:/shared
    environment:
      NODE_ENV: development

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

volumes:
  mariadb: {}
