version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    read_only: true
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.mail-report.schedule: "0 18 * * *"
      ofelia.job-exec.mail-report.command: "npm run mail-report"
      ofelia.job-exec.db-retention.schedule: "@every 1h"
      ofelia.job-exec.db-retention.command: "npm run db-retention"
    environment:
      NODE_ENV: production
      LOCATION_NAME: ${LOCATION_NAME?err}
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      CERTIFICATE_PATH: ${CERTIFICATE_PATH?err}
      ISSUER_BASE_URL: ${OIDC_ISSUER_BASE_URL?err}
      CLIENT_ID: ${OIDC_CLIENT_ID?err}
      SECRET: ${OIDC_APP_SECRET?err}
      REPORT_MAIL: ${REPORT_MAIL?err}
      SMTP_CONNECTION: ${SMTP_CONNECTION?err}
      SMTP_FROM: ${SMTP_FROM?err}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID?err}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN?err}
      TWILIO_SMS_FROM: ${TWILIO_SMS_FROM?err}
      WEB_DOMAIN: ${WEB_DOMAIN?err}
      WEB_PROTO: ${WEB_PROTO:-https}
      WEB_PORT: ${WEB_PORT:-443}
      WEB_PATH: ${WEB_PATH:-/}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        REACT_APP_LOCATION_NAME: ${LOCATION_NAME?err}
        REACT_APP_LOGO_REF: ${LOGO_REF:-/logo.png}
        REACT_APP_INDEX_REF: ${INDEX_REF:-/location.html}
        REACT_APP_IMPRINT_REF: ${IMPRINT_REF?err}
        REACT_APP_PRIVACY_REF: ${PRIVACY_REF?err}
        REACT_APP_TEST_DURATION: ${TEST_DURATION:-900}
        REACT_APP_THEME_PRIMARY: ${THEME_PRIMARY:-#152968}
        REACT_APP_THEME_ON_PRIMARY: ${THEME_ON_PRIMARY:-#FFF}
        REACT_APP_THEME_SECONDARY: ${THEME_SECONDARY:-#25a534}
        REACT_APP_THEME_ON_SECONDARY: ${THEME_ON_SECONDARY:-#FFF}
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /run
      - /etc/nginx/conf.d
    ports:
      - "${HOST_WEB_PORT:-80}:80"

  db:
    image: mariadb
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /run/mysqld
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

volumes:
  mariadb: {}
