version: '3.8'

services:
  node:
    build: ./node
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      ISSUER_BASE_URL: ${ISSUER_BASE_URL}
      CLIENT_ID: ${ISSUER_BASE_URL}
      BASE_URL: ${ISSUER_BASE_URL}
      SECRET: ${ISSUER_BASE_URL}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

volumes:
  mariadb: {}
