version: '3.8'

services:
  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      ISSUER_BASE_URL: ${ISSUER_BASE_URL}
      CLIENT_ID: ${CLIENT_ID}
      BASE_URL: ${BASE_URL}
      SECRET: ${SECRET}

  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile-test
    restart: unless-stopped
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      ISSUER_BASE_URL: ${ISSUER_BASE_URL}
      CLIENT_ID: ${CLIENT_ID}
      BASE_URL: ${BASE_URL}
      SECRET: ${SECRET}

  api-test:
    build:
      context: ./oidc-mock
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9090"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-web
    restart: unless-stopped
    volumes:
      - ./web/userfrontend/build:/var/www/html/
      - ./web/adminfrontend/build:/var/www/html/admin
      - ./web/templates:/etc/nginx/templates
    ports:
      - "${WEB_PORT:-80}:80"

  build-admin:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-adminbuild
    restart: unless-stopped
    volumes:
      - ./web/adminfrontend:/app
    environment:
      NODE_ENV: development

  build-user:
    build:
      context: ./web
      dockerfile: Dockerfile-dev-userbuild
    restart: unless-stopped
    volumes:
      - ./web/userfrontend:/app
    environment:
      NODE_ENV: development

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

volumes:
  mariadb: {}
