version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    read_only: true
    environment:
      NODE_ENV: production
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}
      ISSUER_BASE_URL: ${OIDC_ISSUER_BASE_URL?err}
      CLIENT_ID: ${OIDC_CLIENT_ID?err}
      BASE_URL: ${OIDC_APP_BASE_URL?err}
      SECRET: ${OIDC_APP_SECRET?err}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /run
      - /etc/nginx/conf.d
    ports:
      - "${WEB_PORT:-80}:80"

  db:
    image: mariadb
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /run/mysqld
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER:-coronatests}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD:-true}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-coronatests}

volumes:
  mariadb: {}
